export const USER_SERVICE_CLIENT = Symbol('USER_SERVICE_CLIENT');
export const PRODUCT_SERVICE_CLIENT = Symbol('PRODUCT_SERVICE_CLIENT');
export const NOTIFICATION_SERVICE_CLIENT = Symbol('NOTIFICATION_SERVICE_CLIENT');
